# Generated by Django 3.2.5 on 2021-07-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_register_name', models.CharField(max_length=30)),
                ('error_equip_name', models.CharField(max_length=30)),
                ('error_content', models.TextField()),
            ],
        ),
    ]
